name: metro_link
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.6.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # State management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  # Local storage
  sqflite: ^2.3.0
  path_provider: ^2.1.1

  # NFC package
  flutter_nfc_kit: ^3.3.1

  # UI utilities
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9

  # Others
  intl: ^0.19.0
  get_it: ^7.6.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Uncomment this when you have assets
  # assets:
  #   - assets/images/